name: website
description: "Kyohei Nakamura のウェブサイト。"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  hooks_riverpod: ^2.4.8
  flutter_hooks: ^0.20.3
  riverpod_annotation: ^2.3.2
  record: ^5.0.1
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.25.0
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.6
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.8
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
